language: php

php:
  - 7.0
  - 7.1
  - 7.2
env:  
  - LARAVEL_VERSION=5.5.*  
  - LARAVEL_VERSION=5.6.*
matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - composer update
script:
  - phpunit